### ISSUE TITLE
Your name is spelled wrong....

### ISSUE THREAD

**Issue by dkulp** [GEUSA/xmodels#2]
In:
https://github.com/GEUSA/xmodels/blob/master/geusa-xlights.xml

You are shown as "Gilber Engineering" without the "t".

**Comment by GEUSA** [comment]
Yes sir. I will fix. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by priemd** [comment]
Fixed, thanks for the heads up!
